 ### Creates A new Patient Entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name" : "John with billing account",
  "email" : "mizu@129gmail.com",
  "address" : "101 Church Street",
  "dateOfBirth": "1996-08-20",
  "registeredDate": "2025-11-20"
}

###