 ### Creates A new Patient Entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "id": "4dd6a0b9-01f1-4d2c-95fe-ea812ef7ac82",
  "name": "John Cena Kafka Test",
  "email": "kafkatest_88@example.com",
  "address": "123 main street22",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}
###